### PR TITLE
Reorder items in tray menu

### PR DESCRIPTION
**Pull request by mulm**
Usability improvement:  move most often used items,
Toggle and Undock, at the top.

### CODE REVIEW

**Comment by Daxx** [comment]
Then "Toggle" would be farthest away from the tray icon (?)
Are you convinced about this? I don't use Toggle ever because single-click on the tray icon toggles.
I never (hardly ever) undock (just undock all).
I'd prefer "Close" to be farthest away to prevent accidental use.
Seems too much like personal preference for repo commit but you've shown others how they can do it, if they would like to.

**Comment by mulm** [comment]
ah... a few things going on here, probably all due to fact that I'm using xubuntu (xfce4 desktop)...

- My tray is in my xfce4-panel which is at TOP of screen so TOP-most item is closest to tray icon, whereas sounds like your tray is at bottom of screen based on your previous comment
- My tray implementation is the XFCE4 "Status Notifier" plugin which has a Setting "Menu is primary action" which was checked.  Which meant that single-click on tray icon didn't toggle, as designed, but brought up menu.

The single-click is a much better implementation and now that I've found out how to get that behavior (by disabling "Menu is primary action"), this PR becomes fairly worthless.

**Comment by mulm** [comment]
Closing per previous comment (PR not needed).

**Comment by Daxx** [comment]
Thanks for feedback.

**Pull request closed without merging**
