### PR TITLE
Provide project manual "man page" (first draft)

### PR DESCRIPTION
**Pull request by Daxx**
kdocker.1      - man page generated from ...
kdocker.pod    - template, using ...
kdocker_man.sh - pod2man shell script

Something to start from?

Dave

### CODE REVIEW

**Comment by Daxx** [comment]
Looks similar to this:

```
KDOCKER(1)                       General Commands Manual                       KDOCKER(1)

NAME
        kdocker - dock any application in the system tray

SYNOPSIS
       kdocker [options]

DESCRIPTION
        KDocker is a program that will dock any application to the system tray

OPTIONS
       -a
            Show author information

       -b
            Suppress the warning dialog when docking non-normal windows (blind mode)

       -d secs
            Maximum time in seconds to allow for a command to start and open a window
            [default: 5 seconds]

       -e type
            Name matching syntax. Choices are:
             n = normal, substring matching [default]
             r = regex (regular expression)
             u = unix wildcard
             w = wildcard
             x = W3C XML Schema 1.1

       -f
            Dock window that has focus (active window)

       -h
            Display this help, then exit

       -i file
            Custom icon path

       -j
            Case sensitive name (title) matching

       -k
            Regex minimal matching

       -l
            Iconify when focus lost

       -m
            Keep application window showing (don't hide on dock)

       -n name
            Match window based on its title

       -o
            Iconify when obscured by other windows

       -p secs
            By default, when the title of the application changes,
            a popup is displayed from the system tray for 4 seconds
            Works well with xmms

       -q
            Disable ballooning title changes (quiet)

       -r
            Remove this application from the pager

       -s
            Make the window sticky (appears on all desktops)

       -t
            Remove this application from the taskbar

       -v, --version
            Show the KDocker version string and exit

       -w wid
            Window id of the application to dock.
            Assumes hex number of the form 0x###...

       -x pid
            Process id of the application to dock.
            Assumes decimal number of the form ###...

AUTHOR
        KDocker was written by Girish Ramakrishnan.
        Revised and maintained by John Schember.

REPORTING BUGS
       Bugs and wishes to the KDocker Home Page <https://github.com/user-none/KDocker>

Version 4.9                           10 March, 2015                           KDOCKER(1)
```

**Comment by Daxx** [comment]
https://bugs.launchpad.net/ubuntu/+source/kdocker/+bug/590577 :)

**Comment by rapgro** [comment]
I used help2man for the v4.8 package in Fedora.

**Comment by Daxx** [comment]
@rapgro - Useful to know, thanks, but a more detailed man page gives the user somewhere to go when "kdocker -h" is not enough.  A few examples of usage would be nice to have included on it.

**Comment by rapgro** [comment]
:+1:

**Pull request merged**
