### PR TITLE
Fetch icon from _NET_WM_ICON if not in WM_CLASS

### LINKED ISSUE #128: Use application icon
kdocker-5.4, Linux

Please add an option to just use the application icon as kdocker icon in the tray. Currently I always need to set an icon for each application and save that setting.

### PR DESCRIPTION
**Pull request by Misko-2083**
also removed XpmCreateDataFromPixmap
fixes #128

### CODE REVIEW

**Comment by Daxx** [comment]
Hi Misko,

Is this based on code from another project or have you researched it yourself?

Looks fine but I can't tell if it will work with a variety of X11 window managers.

My suggestion to try [QIcon::fromTheme()](https://doc.qt.io/qt-5/qicon.html#fromTheme) might not be useful according to [this StackOverflow answer](https://stackoverflow.com/a/12825838/4379802) and I wonder if your implementation improves on that.

Thanks, anyway.
Apologies for asking questions if English is not your first language.

**Comment by Misko-2083** [comment]
Should work on all, because it retrieves the icon data from X11 window hints and properties in ARGB format and converts to Qt format Qrgb. Some older applications or simpler ones may set their icon using WM hints. Many modern applications set their icons using the _NET_WM_ICON property. So trying both methods ensures we cover both cases.

**Review by Daxx — APPROVED** [review]
Before this fix, there were a few apps on KDE that KDocker failed to find icons for. KCalc was one of them which can now be found along with the others*.

\* But see my next comment.

**Review by Daxx — COMMENTED** [review]
Oh, wait ... It used to pick up the icon for [Sublime Text](https://www.sublimetext.com/) but now it returns what seems to be a fully transparent icon matching the background of either a light or dark desktop theme.

**Comment by Daxx** [comment]
Problem seems to be with Gnome app icons on non-Gnome systems (? - Don't hold me to that)

Thunderbird toolkit is XUL, which is GTK-based (so I read)
Sublime Text is also a GTK app.

**Comment by user-none** [comment]
> Problem seems to be with Gnome app icons on non-Gnome systems (? - Don't hold me to that)
> 
> Thunderbird toolkit is XUL, which is GTK-based (so I read) Sublime Text is also a GTK app.
> 
> If anyone want to try debugging this, here's an app to test with:
> 
> `sudo apt install gnome-calculator`

I'm not sure this is the case. I actually tested on KDE with gnome-calculator specifically. Along with a variety of Qt, GTK, and other apps. I did some testing with other DEs too but it was primarily KDE (as usual). I just tested gnome-calculator again and it's still working for me. :-/

I have an idea of maybe a fix but I won't have it ready until this evening.

**Pull request merged**
